services:
  mysql:
    container_name: webservice01_database
    user: 501:20
    image: mysql:8.0.33
    ports:
      - 3306:3306
    volumes:
      # - ./docker/db/webservice01:/var/lib/mysql:rw # docker mysql 의 데이터를 해당 경로에 백업한다.
      - ./src/main/resources/initdb:/docker-entrypoint-initdb.d
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: webservice01